package com.brainacademy.gui.app.ui.forms;

import com.brainacademy.gui.app.model.Route;
import com.brainacademy.gui.app.repository.RouteRepository;
import com.brainacademy.gui.app.ui.dialogs.AddRouteDialog;
import com.brainacademy.gui.app.ui.dialogs.WaitDialog;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.util.concurrent.CancellationException;

import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.border.EmptyBorder;

@Component
public class RoutesForm
        extends BaseForm {

    private static final Logger LOG = LoggerFactory.getLogger(RoutesForm.class);

    @Autowired
    private RouteRepository routeRepository;

    @Autowired
    private AddRouteDialog addRouteDialog;

    private JPanel mainPanel;
    private JTable table1;
    private RoutesTableModel routesTableModel;

    private JDialog waitDialog;
    private Frame parentFrame;
    private SwingWorker<Iterable<Route>, Integer> worker;

    public RoutesForm() {
        $$$setupUI$$$();
        this.setLayout(new GridLayout());
        this.setBorder(new EmptyBorder(12, 12, 12, 12));
        this.add($$$getRootComponent$$$());
    }


    private void createUIComponents() {
        routesTableModel = new RoutesTableModel();
        table1 = new JTable(routesTableModel);

        parentFrame = (Frame) SwingUtilities.getRoot(this);

        waitDialog = new WaitDialog(e -> {
            if (worker != null) {
                worker.cancel(true);
            }
        });
        waitDialog.setLocationRelativeTo(parentFrame);
    }

    @Override
    public void updateData() {

        worker = new SwingWorker<Iterable<Route>, Integer>() {
            @Override
            protected Iterable<Route> doInBackground()
                    throws Exception {
                return routeRepository.findAll();
            }

            @Override
            protected void done() {
                if (waitDialog.isVisible()) {
                    waitDialog.setVisible(false);
                }

                try {
                    routesTableModel.setRoutes(get());
                } catch (CancellationException e) {
                    LOG.warn("Cancel worker task");
                } catch (Exception e) {
                    LOG.error("Unable to load data", e);
                    JOptionPane.showMessageDialog(RoutesForm.this,
                            "Unable to get result",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        };
        worker.execute();
        waitDialog.setVisible(true);
    }

    @Override
    protected void initActions() {
        actions.add(new AbstractAction("Add") {
            @Override
            public void actionPerformed(ActionEvent e) {
                addRouteDialog.setLocationRelativeTo(parentFrame);
                addRouteDialog.setVisible(true);

                updateData();
            }
        });

        actions.add(new AbstractAction("Search") {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        actions.add(new AbstractAction("Remove") {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(table1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
